apiVersion: v1
kind: Service
metadata:
  name: example-cluster-service
  namespace: example-namespace

spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376
      name: test-example
